# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Machine Learning - Photos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Machine Learning - Photos

pod 'Alamofire', '~> 5.2'
pod 'SwiftyJSON', '~> 4.0'
pod 'SDWebImageSwiftUI'

  target 'Machine Learning - PhotosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Machine Learning - PhotosUITests' do
    # Pods for testing
  end

end
